// ─── Level bank ──────────────────────────────────────────────
// Ch. I–II are hand-made; ch. III–V were discovered by the generator,
// certified by `bun run verify`: unsolvable without merge (III+)
// and without split (as marked). Ch. VI: the world itself moves.
// Ch. VII: the magenta film reads mirrored (verso). Ch. VIII:
// registration pins snap the offset home (repere, over decalage).
// Display names live here (also printed by the solver CLI); level
// hints are UI-only and live in the i18n messages, keyed by id.

import type { Level } from './types.ts'

export const LEVELS: Level[] = [
  { id: 'accord', ch: 'I', name: 'Accord', size: 5, mods: [],
    a: { start: [4, 0], goal: [0, 0], walls: [] },
    b: { start: [4, 4], goal: [0, 4], walls: [] } },
  { id: 'retenue', ch: 'I', name: 'Retenue', size: 5, mods: [],
    a: { start: [2, 0], goal: [2, 4], walls: [] },
    b: { start: [2, 0], goal: [2, 2], walls: [[2, 3]] } },
  { id: 'croisee', ch: 'I', name: 'Croisée', size: 5, mods: [],
    a: { start: [0, 0], goal: [4, 4], walls: [] },
    b: { start: [0, 4], goal: [4, 0], walls: [[4, 1]] } },
  { id: 'ecart', ch: 'I', name: 'Écart', size: 5, mods: [],
    a: { start: [0, 2], goal: [4, 2], walls: [[2, 2]] },
    b: { start: [0, 2], goal: [4, 2], walls: [] } },
  { id: 'rdv', ch: 'I', name: 'Rendez-vous', size: 5, mods: [],
    a: { start: [4, 0], goal: [0, 4], walls: [[0, 2]] },
    b: { start: [4, 4], goal: [0, 4], walls: [[1, 4]] } },
  { id: 'blanc', ch: 'II', name: 'Blanc', size: 5, mods: ['fusion', 'scission'],
    a: { start: [4, 1], goal: [0, 2], walls: [[2, 2], [1, 2]] },
    b: { start: [4, 3], goal: [0, 2], walls: [[2, 2], [1, 2]] } },
  { id: 'traversee', ch: 'II', name: 'Traversée', size: 5, mods: ['fusion', 'scission'],
    a: { start: [4, 0], goal: [0, 2], walls: [[2, 0], [2, 1], [2, 2], [2, 3], [2, 4]] },
    b: { start: [4, 4], goal: [0, 2], walls: [[2, 0], [2, 1], [2, 2], [2, 3], [2, 4]] } },
  { id: 'diffraction', ch: 'II', name: 'Diffraction', size: 5, mods: ['fusion', 'scission'],
    a: { start: [4, 0], goal: [1, 4], walls: [[0, 4], [1, 3]] },
    b: { start: [0, 0], goal: [3, 4], walls: [[4, 4], [3, 3]] } },
  { id: 'trouvaille', ch: 'III', name: 'Trouvaille', size: 5, mods: ['fusion', 'scission'],
    a: { start: [0, 0], goal: [0, 4], walls: [[4, 2], [0, 3], [1, 0], [0, 1]] },
    b: { start: [2, 4], goal: [4, 4], walls: [[0, 4], [0, 2], [3, 1]] } },
  { id: 'abysse', ch: 'III', name: 'Abysse', size: 5, mods: ['fusion', 'scission'],
    a: { start: [0, 0], goal: [4, 1], walls: [[3, 1], [0, 3], [0, 1], [1, 0], [3, 3]] },
    b: { start: [4, 4], goal: [0, 4], walls: [[4, 3], [1, 4]] } },
  { id: 'eclipse', ch: 'IV', name: 'Éclipse', size: 5,
    mods: ['fusion', 'scission', 'lumiere'], lightWalls: [[1, 2], [1, 1], [0, 1]],
    a: { start: [0, 3], goal: [1, 0], walls: [[1, 1], [3, 1], [3, 4]] },
    b: { start: [4, 0], goal: [4, 4], walls: [[4, 2], [1, 4], [3, 1], [3, 0], [3, 4]] } },
  { id: 'echange', ch: 'IV', name: 'Échange', size: 5,
    mods: ['fusion', 'scission', 'lumiere'], lightWalls: [[1, 1]],
    a: { start: [0, 0], goal: [4, 4], walls: [[1, 0], [4, 3], [1, 1], [0, 2]] },
    b: { start: [4, 4], goal: [0, 0], walls: [[4, 3], [1, 0], [2, 0], [3, 1], [1, 3]] } },
  { id: 'trinite', ch: 'V', name: 'Trinité', size: 5,
    mods: ['fusion', 'scission', 'lumiere', 'glace'], lightWalls: [[3, 0], [0, 3]],
    a: { start: [4, 1], goal: [4, 1], walls: [[1, 2], [4, 4], [2, 2], [1, 1]] },
    b: { start: [4, 4], goal: [4, 2], walls: [[0, 1], [4, 0], [2, 2], [4, 3], [3, 2]] } },
  { id: 'verglas', ch: 'V', name: 'Verglas', size: 5,
    mods: ['fusion', 'scission', 'lumiere', 'glace'], lightWalls: [[1, 2], [1, 3]],
    a: { start: [3, 3], goal: [2, 0], walls: [[0, 2], [3, 4], [4, 1], [2, 3], [3, 0]] },
    b: { start: [0, 2], goal: [2, 0], walls: [[4, 0], [3, 2], [2, 3], [2, 4]] } },
  { id: 'derive', ch: 'VI', name: 'Dérive', size: 5,
    mods: ['fusion', 'scission', 'decalage'],
    a: { start: [1, 2], goal: [2, 0], walls: [[4, 2], [2, 2], [1, 1]] },
    b: { start: [4, 1], goal: [0, 4], walls: [[3, 1], [0, 0], [1, 2], [2, 0], [4, 2]] } },
  { id: 'tectonique', ch: 'VI', name: 'Tectonique', size: 5,
    mods: ['fusion', 'scission', 'decalage'],
    a: { start: [0, 4], goal: [4, 4], walls: [[2, 4], [1, 3], [0, 3], [0, 2], [1, 4]] },
    b: { start: [2, 1], goal: [1, 0], walls: [[2, 2], [0, 2], [1, 2], [3, 2], [4, 4], [0, 1], [0, 4]] } },
  { id: 'reflet', ch: 'VII', name: 'Reflet', size: 5, mods: ['verso'],
    a: { start: [3, 0], goal: [4, 4], walls: [[0, 4], [1, 2], [4, 0]] },
    b: { start: [2, 4], goal: [2, 1], walls: [[1, 0], [0, 1], [0, 3]] } },
  { id: 'envers', ch: 'VII', name: 'Envers', size: 5, mods: ['fusion', 'scission', 'verso'],
    a: { start: [0, 4], goal: [4, 0], walls: [[1, 1], [1, 4], [2, 2], [3, 1], [0, 3]] },
    b: { start: [2, 1], goal: [0, 4], walls: [[2, 3], [1, 3], [0, 2]] } },
  { id: 'parallaxe', ch: 'VII', name: 'Parallaxe', size: 5, mods: ['fusion', 'scission', 'verso', 'glace'],
    a: { start: [4, 4], goal: [0, 1], walls: [[4, 2], [3, 4], [2, 1]] },
    b: { start: [2, 0], goal: [0, 1], walls: [[0, 2], [1, 1], [4, 3], [4, 0]] } },
  { id: 'goupille', ch: 'VIII', name: 'Goupille', size: 5,
    mods: ['fusion', 'scission', 'decalage', 'repere'], pins: [[4, 0], [3, 2]],
    a: { start: [2, 3], goal: [4, 0], walls: [[4, 4], [3, 0], [2, 4]] },
    b: { start: [4, 1], goal: [1, 3], walls: [[0, 4], [0, 1], [2, 4], [2, 3]] } },
  { id: 'aplomb', ch: 'VIII', name: 'Aplomb', size: 5,
    mods: ['fusion', 'scission', 'decalage', 'repere'], pins: [[4, 4], [2, 0]],
    a: { start: [4, 4], goal: [1, 1], walls: [[4, 1], [1, 0], [0, 0], [0, 3]] },
    b: { start: [0, 0], goal: [4, 3], walls: [[2, 3], [3, 4], [0, 4], [0, 1], [1, 0], [3, 3]] } },
  { id: 'calage', ch: 'VIII', name: 'Calage', size: 5,
    mods: ['fusion', 'scission', 'decalage', 'repere', 'glace'], pins: [[2, 1], [0, 4]],
    a: { start: [2, 3], goal: [0, 4], walls: [[0, 1], [3, 3], [4, 3]] },
    b: { start: [1, 4], goal: [1, 0], walls: [[4, 1], [3, 2], [3, 1], [2, 0]] } },
]
