// Drizzle schema. The four auth tables (user / session / account /
// verification) are generated by the Better Auth CLI (`bun run auth:generate`)
// and must match what better-auth expects — do not hand-edit their shape.
// The daily and campaign tables below are ours. Note: re-running auth:generate
// rewrites this whole file, so re-append ALL of our tables from git afterward —
// dailyPuzzle, dailyScore, and levelScore.

import {
  pgTable,
  text,
  integer,
  serial,
  jsonb,
  timestamp,
  boolean,
  index,
  uniqueIndex,
  primaryKey,
  foreignKey,
} from "drizzle-orm/pg-core";
import type { Level, TraceStep } from "../engine/types.ts";

// ─── Better Auth tables (generated by `bun run auth:generate`) ────
export const user = pgTable("user", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  email: text("email").notNull().unique(),
  emailVerified: boolean("email_verified").default(false).notNull(),
  image: text("image"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at")
    .defaultNow()
    .$onUpdate(() => new Date())
    .notNull(),
});

export const session = pgTable(
  "session",
  {
    id: text("id").primaryKey(),
    expiresAt: timestamp("expires_at").notNull(),
    token: text("token").notNull().unique(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at")
      .$onUpdate(() => new Date())
      .notNull(),
    ipAddress: text("ip_address"),
    userAgent: text("user_agent"),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
  },
  (t) => [index("session_userId_idx").on(t.userId)],
);

export const account = pgTable(
  "account",
  {
    id: text("id").primaryKey(),
    accountId: text("account_id").notNull(),
    providerId: text("provider_id").notNull(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    accessToken: text("access_token"),
    refreshToken: text("refresh_token"),
    idToken: text("id_token"),
    accessTokenExpiresAt: timestamp("access_token_expires_at"),
    refreshTokenExpiresAt: timestamp("refresh_token_expires_at"),
    scope: text("scope"),
    password: text("password"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at")
      .$onUpdate(() => new Date())
      .notNull(),
  },
  (t) => [index("account_userId_idx").on(t.userId)],
);

export const verification = pgTable(
  "verification",
  {
    id: text("id").primaryKey(),
    identifier: text("identifier").notNull(),
    value: text("value").notNull(),
    expiresAt: timestamp("expires_at").notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at")
      .defaultNow()
      .$onUpdate(() => new Date())
      .notNull(),
  },
  (t) => [index("verification_identifier_idx").on(t.identifier)],
);

// ─── Daily puzzle tables (ours) ──────────────────────────────

/** Three shared levels per UTC day (one per difficulty tier), written by the
 *  cron generator. `tier` is 0 (easy) · 1 (medium) · 2 (hard); the pair
 *  (date, tier) identifies a puzzle. Rows predating the tiered generator default
 *  to tier 1 — the old single daily was the ~16-move "medium". */
export const dailyPuzzle = pgTable(
  "daily_puzzle",
  {
    date: text("date").notNull(), // YYYY-MM-DD (UTC)
    tier: integer("tier").notNull().default(1),
    level: jsonb("level").$type<Level>().notNull(),
    optimal: integer("optimal").notNull(), // solver's optimal move count
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (t) => [primaryKey({ columns: [t.date, t.tier] })],
);

/** A player's best result for a given day's tier. `trace` holds the full raw
 *  play trace (inputs + undo/reset), kept for server-side replay/audit; `undos`
 *  is the correction count the server derived from it (0 = a clean solve). Rank
 *  is moves, then undos. One row per (date, tier, user) — each tier has its own
 *  leaderboard. */
export const dailyScore = pgTable(
  "daily_score",
  {
    id: serial("id").primaryKey(),
    date: text("date").notNull(),
    tier: integer("tier").notNull().default(1),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    moves: integer("moves").notNull(),
    undos: integer("undos").notNull().default(0),
    // physical column is legacy-named "inputs"; it stores the full TraceStep[]
    trace: jsonb("inputs").$type<TraceStep[]>().notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (t) => [
    uniqueIndex("daily_score_date_tier_user").on(t.date, t.tier, t.userId),
    foreignKey({
      columns: [t.date, t.tier],
      foreignColumns: [dailyPuzzle.date, dailyPuzzle.tier],
    }).onDelete("cascade"),
  ],
);

// ─── Campaign leaderboard ────────────────────────────────────

/** A player's best result for a campaign board. `levelId` is the code-side
 *  level id (the LEVELS bank), validated in the server function rather than by
 *  a FK — campaign levels live in code, not the DB. `trace` holds the full raw
 *  play trace (inputs + undo/reset), kept for server-side replay/audit; `undos`
 *  is the correction count the server derived from it (0 = a clean solve). Rank
 *  is moves, then undos. One row per (level, user). */
export const levelScore = pgTable(
  "level_score",
  {
    id: serial("id").primaryKey(),
    levelId: text("level_id").notNull(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    moves: integer("moves").notNull(),
    undos: integer("undos").notNull().default(0),
    // physical column is legacy-named "inputs"; it stores the full TraceStep[]
    trace: jsonb("inputs").$type<TraceStep[]>().notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (t) => [uniqueIndex("level_score_level_user").on(t.levelId, t.userId)],
);
