// Vite plugin: emits sw.js into the client build. vite-plugin-pwa can't be
// used here — its Workbox step globs the vite client outDir, but Nitro
// relocates the assets and builds a *build-time* static-asset registry, so a
// file written after the build is never served (and TanStack Start's data-only
// SSR emits no static index.html for Workbox's navigateFallback). Emitting the
// SW inside the client `generateBundle` puts it in the bundle Nitro copies to
// .output/public and registers — and gives us the hashed asset names directly.
//
// The game engine and all 16 levels ship inside the JS bundle, so precaching
// the shell + built assets makes the campaign fully playable offline for free.
// The daily mode stays online-only (its routes hit server functions under the
// network-only /api path and the getDaily* server functions).

import { createHash } from "node:crypto";
import type { Plugin } from "vite";

// Stable-named files copied from public/ by Nitro (not part of the JS bundle),
// plus "/" — the SSR app shell, precached and used as the offline navigation
// fallback so any client route (/, /levels, /level/N) renders offline.
const SHELL = [
  "/",
  "/favicon.svg",
  "/manifest.webmanifest",
  "/apple-touch-icon.png",
  "/pwa-192.png",
  "/pwa-512.png",
  "/pwa-maskable-512.png",
];

function template(cache: string, precache: string[]): string {
  return `// Generated by scripts/sw-plugin.ts — do not edit.
const CACHE = ${JSON.stringify(cache)};
const PRECACHE = ${JSON.stringify(precache)};

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(CACHE).then((cache) => cache.addAll(PRECACHE)).then(() => self.skipWaiting()),
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener("fetch", (event) => {
  const req = event.request;
  if (req.method !== "GET") return;
  const url = new URL(req.url);
  // Cross-origin (e.g. Google Fonts) and the whole server API stay network-only:
  // never cache /api or the daily/auth/leaderboard server functions.
  if (url.origin !== self.location.origin) return;
  if (url.pathname.startsWith("/api")) return;

  // Client navigations: network-first (keeps online SSR and the daily live),
  // caching each visited route; offline, serve the exact page then the "/"
  // app shell so a never-visited campaign route still renders.
  if (req.mode === "navigate") {
    event.respondWith(
      fetch(req)
        .then((res) => {
          const copy = res.clone();
          caches.open(CACHE).then((cache) => cache.put(req, copy));
          return res;
        })
        .catch(() => caches.match(req).then((hit) => hit || caches.match("/"))),
    );
    return;
  }

  // Hashed static assets are immutable: serve from cache, fall back to network.
  event.respondWith(caches.match(req).then((hit) => hit || fetch(req)));
});
`;
}

export function serviceWorker(): Plugin {
  return {
    name: "superposition:service-worker",
    apply: "build",
    generateBundle(_options, bundle) {
      // Only the browser build; the ssr/server environments must not emit a SW.
      if (this.environment.name !== "client") return;
      const assets = Object.keys(bundle)
        .filter((name) => /\.(js|css|woff2?)$/.test(name))
        .map((name) => "/" + name);
      const precache = [...SHELL, ...assets].sort();
      // Cache name keyed to the precached set (hashed filenames included): a new
      // build changes the hash, so activate() drops the old cache — silent
      // auto-update, no prompt (it's a game, not critical data).
      const cache =
        "superposition-" +
        createHash("sha256").update(precache.join()).digest("hex").slice(0, 12);
      this.emitFile({
        type: "asset",
        fileName: "sw.js",
        source: template(cache, precache),
      });
    },
  };
}
