/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LevelsRouteImport } from './routes/levels'
import { Route as AlignRouteImport } from './routes/align'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LevelPlateRouteImport } from './routes/level.$plate'
import { Route as DailyTierRouteImport } from './routes/daily.$tier'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const LevelsRoute = LevelsRouteImport.update({
  id: '/levels',
  path: '/levels',
  getParentRoute: () => rootRouteImport,
} as any)
const AlignRoute = AlignRouteImport.update({
  id: '/align',
  path: '/align',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LevelPlateRoute = LevelPlateRouteImport.update({
  id: '/level/$plate',
  path: '/level/$plate',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyTierRoute = DailyTierRouteImport.update({
  id: '/daily/$tier',
  path: '/daily/$tier',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/align': typeof AlignRoute
  '/levels': typeof LevelsRoute
  '/daily/$tier': typeof DailyTierRoute
  '/level/$plate': typeof LevelPlateRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/align': typeof AlignRoute
  '/levels': typeof LevelsRoute
  '/daily/$tier': typeof DailyTierRoute
  '/level/$plate': typeof LevelPlateRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/align': typeof AlignRoute
  '/levels': typeof LevelsRoute
  '/daily/$tier': typeof DailyTierRoute
  '/level/$plate': typeof LevelPlateRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/align'
    | '/levels'
    | '/daily/$tier'
    | '/level/$plate'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/align'
    | '/levels'
    | '/daily/$tier'
    | '/level/$plate'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/align'
    | '/levels'
    | '/daily/$tier'
    | '/level/$plate'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlignRoute: typeof AlignRoute
  LevelsRoute: typeof LevelsRoute
  DailyTierRoute: typeof DailyTierRoute
  LevelPlateRoute: typeof LevelPlateRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/levels': {
      id: '/levels'
      path: '/levels'
      fullPath: '/levels'
      preLoaderRoute: typeof LevelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/align': {
      id: '/align'
      path: '/align'
      fullPath: '/align'
      preLoaderRoute: typeof AlignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/level/$plate': {
      id: '/level/$plate'
      path: '/level/$plate'
      fullPath: '/level/$plate'
      preLoaderRoute: typeof LevelPlateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily/$tier': {
      id: '/daily/$tier'
      path: '/daily/$tier'
      fullPath: '/daily/$tier'
      preLoaderRoute: typeof DailyTierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlignRoute: AlignRoute,
  LevelsRoute: LevelsRoute,
  DailyTierRoute: DailyTierRoute,
  LevelPlateRoute: LevelPlateRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
